1. SELECT C.CODCARRERA , A.TANTOPORUNO FROM CARRERAS c , APUESTAS a WHERE A.TANTOPORUNO >3 AND C.CODCARRERA = A.CODCARRERA 
2. SELECT NOMBRE , APELLIDOS FROM PERSONAS p WHERE FECHA_NACIMIENTO > '01-01-0080' ORDER BY FECHA_NACIMIENTO DESC
3. SELECT DISTINCT CODCABALLO FROM  PARTICIPACIONES p WHERE P.POSICIONFINAL <=3  ORDER BY CODCABALLO 
4. SELECT * FROM  CARRERAS c WHERE IMPORTEPREMIO >5000
5. SELECT NOMBRE ,DNI FROM CLIENTES c WHERE NACIONALIDAD !='Britanica' AND NACIONALIDAD !='Escocesa'
6. SELECT P.CODIGO , C.NOMBRE FROM CABALLOS c , PERSONAS p WHERE P.CODIGO =C.PROPIETARIO AND (C.FECHANACIMIENTO LIKE('%-11-__%') OR C.PESO >=260) ORDER BY P.CODIGO DESC , C.NOMBRE ASC
7. SELECT DISTINCT P.NOMBRE FROM PERSONAS p WHERE P.NOMBRE LIKE ('%J%e%')
8. SELECT DISTINCT C.CODCABALLO FROM CABALLOS c , PARTICIPACIONES p WHERE C.CODCABALLO =P.CODCABALLO AND P.POSICIONFINAL =1 GROUP BY C.CODCABALLO HAVING COUNT(P.POSICIONFINAL)> 1
9. SELECT MAX(C.IMPORTEPREMIO) FROM CARRERAS c  
10. SELECT MAX(A.IMPORTE*A.TANTOPORUNO) AS PREMIO FROM APUESTAS a , CARRERAS c2 , PARTICIPACIONES p WHERE A.CODCARRERA = C2.CODCARRERA AND C2.CODCARRERA = P.CODCARRERA 
AND P.POSICIONFINAL =1  
11. SELECT C.NOMBRE  , SUM(A.IMPORTE *A.TANTOPORUNO) AS DINERO_GANADO FROM APUESTAS a , CARRERAS c2 , PARTICIPACIONES p, CLIENTES c WHERE A.CODCARRERA = C2.CODCARRERA AND C2.CODCARRERA = P.CODCARRERA 
AND C.DNI = A.DNICLIENTE AND P.POSICIONFINAL =1  GROUP BY C.NOMBRE 
12. SELECT  P2.NOMBRE , P2.APELLIDOS , C.NOMBRE FROM PARTICIPACIONES p , PERSONAS p2 , CABALLOS c  WHERE P.JOCKEY = P2.CODIGO  AND P.POSICIONFINAL =1 AND C.CODCABALLO = P.CODCABALLO 
13. SELECT DISTINCT P2.NOMBRE, P2.APELLIDOS FROM PARTICIPACIONES p , PERSONAS p2, CABALLOS c WHERE P.JOCKEY = P2.CODIGO AND P2.CODIGO =C.PROPIETARIO 
14. SELECT C.NOMBRECARRERA , C2.NOMBRE , A.IMPORTE FROM CARRERAS c , CLIENTES c2 , APUESTAS a WHERE C.CODCARRERA =A.CODCARRERA AND A.DNICLIENTE =C2.DNI AND A.IMPORTE >C.APUESTALIMITE 
15. SELECT DISTINCT p.NOMBRE , p.APELLIDOS, c.NOMBRE FROM PERSONAS p , CABALLOS c , PARTICIPACIONES p2 WHERE c.CODCABALLO = p2.CODCABALLO  AND c.PROPIETARIO =p.CODIGO GROUP BY p.NOMBRE, p.APELLIDOS , c.NOMBRE HAVING COUNT(c.NOMBRE)>2 --eSTA MAL
16. SELECT DISTINCT C.NOMBRE , C.NACIONALIDAD FROM CLIENTES c , APUESTAS a WHERE C.DNI =A.DNICLIENTE AND A.IMPORTE >800



--APARTADO 2
1. 
/*Las transacciones son un grupo de sentencias que garantizan cambios consistentes en los datos. Pueden ser de los siguientes tipos:
- Grupo de sentencias DML que el servidor ORACLE trata como una única uidad de trabajo.
-Una sentencia DDL
Una sentencia DCL*/


2. 
--Ya lo he comentado en el apartado anterior, por lo que todas las anteriores son tipos de transacciones

3. 
--Todos los anteriores son correctos

4.
--Todas las anteriores son correctas


